---
title: "analyzing_age_bias"
author: "Franziska Hafner"
date: "21/06/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(sf)
library(ggplot2)
library(dplyr)
library(reshape2)
```

```{r}
rm(true_nationality)
rm(predicted_nationality)
rm(nationality_data)

true_nationality <- read.csv("/Users/franziskahafner/Desktop/paper/testing_AI/input/names_to_ethnicity_equal_gender_age_nat_21else.csv")
predicted_nationality <- read.csv("/Users/franziskahafner/Desktop/paper/testing_AI/output/classified_equal_gender_age_nat_21else.csv")

nationality_data <- true_nationality

nationality_data$predicted_nationality <- c()
nationality_data$right_prediction <- c()
for(i in seq(1,nrow(nationality_data))){
  nationality_data$predicted_nationality[i] <- predicted_nationality$ethnicities[i]
  nationality_data$nationality[i] <- gsub(" ", "", nationality_data$nationality[i])
  nationality_data$gender[i] <- gsub(" ", "", nationality_data$gender[i])
  nationality_data$predicted_nationality[i] <- gsub(" ", "", nationality_data$predicted_nationality[i])
  if (nationality_data$nationality[i] == nationality_data$predicted_nationality[i]){
    nationality_data$right_prediction[i] <- 1
  }
  else{
    nationality_data$right_prediction[i] <- 0
  }
}

nationality_data$gender <- as.factor(nationality_data$gender)
nationality_data$year_of_birth <- as.factor(nationality_data$year_of_birth)
```

```{r}
table(nationality_data$year_of_birth)
```

```{r}
decade <- c(levels(as.factor(nationality_data$year_of_birth)))
female_right_predictions <- rep(0,length(decade))
male_right_predictions <- rep(0,length(decade))

right_predictions_per_decade <- data.frame(decade, female_right_predictions, male_right_predictions)

for(i in seq(1,nrow(nationality_data))){
  if(as.character(nationality_data$gender[i])=="female"){
    current_decade <- nationality_data$year_of_birth[i]
    new_value <- right_predictions_per_decade[right_predictions_per_decade$decade==current_decade, "female_right_predictions"] + nationality_data$right_prediction[i]
    right_predictions_per_decade[right_predictions_per_decade$decade==current_decade, "female_right_predictions"] <- new_value
  }
  else{
    current_decade <- nationality_data$year_of_birth[i]
    new_value <- right_predictions_per_decade[right_predictions_per_decade$decade==current_decade, "male_right_predictions"] + nationality_data$right_prediction[i]
    right_predictions_per_decade[right_predictions_per_decade$decade==current_decade, "male_right_predictions"] <- new_value
  }
}
```

```{r}
title <- paste("Gender Differences in Accuracy per Decade ", length(all_nationalities)-1," Nationalities and Else")

p<-ggplot(data=right_predictions_per_decade) +
  geom_bar(stat='identity', aes(x=decade, y=male_right_predictions, fill = "#67c45f")) +
  geom_bar(stat='identity', aes(x=decade, y=female_right_predictions, fill = "#8e8bda"), width = 0.6) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  labs(x="Nationalities", y="Right Predictions (out of 1380)", 
      title=title) +
       scale_fill_manual(name = "Gender", 
                    label = c("Male", "Female"), 
                    values = c("#67c45f", "#8e8bda"))
p
```

```{r}
all_nationalities <- c(levels(as.factor(nationality_data$nationality)))
decade_50s <- rep(0,length(all_nationalities))
decade_60s <- rep(0,length(all_nationalities))
decade_70s <- rep(0,length(all_nationalities))
decade_80s <- rep(0,length(all_nationalities))
decade_90s <- rep(0,length(all_nationalities))

decade_nationality_accuracy <- data.frame(all_nationalities, decade_50s, decade_60s, decade_70s, decade_80s, decade_90s)

for(i in seq(1,nrow(nationality_data))){
  if (nationality_data$year_of_birth[i] == "1950-1959"){
    decade = "decade_50s"
  }
  if (nationality_data$year_of_birth[i] == "1960-1969"){
    decade = "decade_60s"
  }
  if (nationality_data$year_of_birth[i] == "1970-1979"){
    decade = "decade_70s"
  }
  if (nationality_data$year_of_birth[i] == "1980-1989"){
    decade = "decade_80s"
  }
  if (nationality_data$year_of_birth[i] == "1990-1999"){
    decade = "decade_90s"
  }
  
  new_value <- decade_nationality_accuracy[decade_nationality_accuracy$all_nationalities==nationality_data$nationality[i], decade] + nationality_data$right_prediction[i]
  decade_nationality_accuracy[decade_nationality_accuracy$all_nationalities==nationality_data$nationality[i], decade] <- new_value
}

for(nationality in all_nationalities){
  for(decade in c("decade_50s","decade_60s","decade_70s","decade_80s","decade_90s")){
    decade_nationality_accuracy[decade_nationality_accuracy$all_nationalities==nationality, decade] <- (decade_nationality_accuracy[decade_nationality_accuracy$all_nationalities==nationality, decade])/60
  }
}

traff2 <- melt(decade_nationality_accuracy,id=c("all_nationalities"),variable.name = "Year")
colnames(traff2)[1] <- "Nationality"
```


```{r}
p <- ggplot(traff2[traff2$Nationality=="british"|traff2$Nationality=="else"|traff2$Nationality=="chinese"|traff2$Nationality=="german"|traff2$Nationality=="pakistani"|traff2$Nationality=="zimbabwean",], aes(x = Year, y = value, color = Nationality, group = Nationality))+
#facet_grid(facets = Category~., scales = "free_y")+
  geom_line()+theme_bw()+
  labs(x="Year of Birth", y="Accuracy", 
      title="Change in Accuracy for Different Nationalities by Age") +
        scale_x_discrete(labels=c("decade_50s" = "1950-1959", "decade_60s" = "1960-1969",
                              "decade_70s" = "1970-1979", "decade_80s" = "1980-1989","decade_90s" = "1990-1999"))
p
```

```{r}
p <- ggplot(traff2, aes(x = Year, y = value, color = Nationality, group = Nationality))+
#facet_grid(facets = Category~., scales = "free_y")+
  geom_line()+theme_bw()+
  labs(x="Year of Birth", y="Accuracy", 
      title="Change in Accuracy for Different Nationalities by Age") +
        scale_x_discrete(labels=c("decade_50s" = "1950-1959", "decade_60s" = "1960-1969",
                              "decade_70s" = "1970-1979", "decade_80s" = "1980-1989","decade_90s" = "1990-1999"))
p
```


```{r}
traff2[traff2$value<0.75&traff2$Year=="decade_90s",]
```

























